/**
 * The game's static content, loaded from what the Java build exports.
 *
 * `content/*.json` is generated by `./gradlew exportContent` and carries each entry's own
 * `{type|field|field}` source text. Parsing it here rather than shipping a hand-written schema
 * means one grammar for content and saves alike, and no second copy of the data to drift.
 */

import { parseEntity, type Entity, type Field } from "../format/parse.js";
import type { CarriedArms } from "./hero.js";

export interface WeaponDefinition {
  readonly key: string;
  readonly attack: number;
  readonly defend: number;
  readonly skill: number;
  /** `right`, `left`, `head`, `body`, `feet` and the special traits, as written in the content. */
  readonly traits: readonly string[];
}

export interface MonsterDefinition {
  readonly key: string;
  /** Display name, which quest text may override per encounter. */
  readonly name: string;
  readonly guts: number;
  readonly wits: number;
  readonly charm: number;
  readonly baseAttack: number;
  readonly baseDefend: number;
  readonly baseSkill: number;
  /** `passive`, `timid`, `defensive`, `hostile` or `aggressive`. */
  readonly passion: string;
  /** What you may try instead of fighting: bribe, riddle, seduce, trade… */
  readonly options: readonly string[];
  readonly picture: string | null;
  /**
   * The skill counts in the monster's `temp` list, which decide what it tries in a fight — fight,
   * magic, thief, ieatsu — plus how many actions it has.
   */
  readonly skills: ReadonlyMap<string, number>;
  /** What it is carrying, by name. Dust and potions decide what it tries in a fight. */
  readonly carrying: ReadonlyMap<string, number>;
  /**
   * Bare traits sitting in the monster's `gear` list — `panic`, `disease`, `bless`.
   *
   * They are not items but properties of what the creature strikes with, which is why a Harpy makes
   * you sick and a Wyvern sends you running. Written alongside the gear rather than on it, so they
   * come out of the list as loose strings.
   */
  readonly gearTraits: readonly string[];
  /** The flavour text shown when you meet it, with its `$name$`-style slots already chosen. */
  readonly entity: Entity;
}

/**
 * A weapon from the table, as a thing a character can carry.
 *
 * One place rather than four, because a piece of equipment has grown a field twice now and the
 * copies do not all get updated when it does.
 */
export function armsOf(weapon: WeaponDefinition): CarriedArms {
  return {
    kind: "arms",
    name: weapon.key,
    attack: weapon.attack,
    defend: weapon.defend,
    skill: weapon.skill,
    traits: weapon.traits,
    // Anything the table sells is plain. Enchantment is something you do to it afterwards.
    enchant: 0,
    forged: 0,
    tempered: 0,
  };
}

export interface GearDefinition {
  readonly key: string;
  readonly type: number;
  readonly cost: number;
  readonly effect: number;
}

export interface Content {
  readonly weapons: ReadonlyMap<string, WeaponDefinition>;
  readonly monsters: ReadonlyMap<string, MonsterDefinition>;
  readonly gear: ReadonlyMap<string, GearDefinition>;
}

interface RawEntry {
  key: string;
  source: string;
}

function isEntity(field: Field): field is Entity {
  return typeof field !== "string";
}

function num(field: Field | undefined): number {
  return typeof field === "string" ? Number(field) : 0;
}

/** A named sub-list, e.g. `values` or `opts`. */
function listNamed(entity: Entity, name: string): Entity | null {
  for (const field of entity.fields) {
    if (isEntity(field) && field.type === "itList" && field.name === name) {
      return field;
    }
  }
  return null;
}

function valueNamed(entity: Entity, name: string): string | null {
  for (const field of entity.fields) {
    if (isEntity(field) && field.type === "itValue" && field.name === name) {
      const payload = field.fields[0];
      return typeof payload === "string" ? payload : null;
    }
  }
  return null;
}

/** The loose words in a list, as opposed to the entries that carry a value. */
function bareStringsIn(list: Entity | null): string[] {
  if (list === null) {
    return [];
  }
  return list.fields.filter((f): f is string => typeof f === "string" && f.trim().length > 0);
}

/** Named counts in a list, e.g. the skills in `temp`. */
function countsIn(list: Entity | null): Map<string, number> {
  const counts = new Map<string, number>();
  if (list === null) {
    return counts;
  }
  for (const field of list.fields) {
    if (isEntity(field)) {
      counts.set(field.name, num(field.fields[0]));
    }
  }
  return counts;
}

export function weaponFrom(entry: RawEntry): WeaponDefinition {
  const entity = parseEntity(entry.source);
  const [attack, defend, skill, ...rest] = entity.fields;
  return {
    key: entry.key,
    attack: num(attack),
    defend: num(defend),
    skill: num(skill),
    traits: rest.filter((f): f is string => typeof f === "string" && f.length > 0),
  };
}

export function monsterFrom(entry: RawEntry): MonsterDefinition {
  const entity = parseEntity(entry.source);
  const [guts, wits, charm, baseA, baseD, baseS] = entity.fields;
  const values = listNamed(entity, "values");
  const opts = listNamed(entity, "opts");
  return {
    key: entry.key,
    name: entity.name,
    guts: num(guts),
    wits: num(wits),
    charm: num(charm),
    baseAttack: num(baseA),
    baseDefend: num(baseD),
    baseSkill: num(baseS),
    // An unrecognised passion makes the monster defensive, which is what the Java falls back to.
    passion: (values === null ? null : valueNamed(values, "passion")) ?? "defensive",
    options:
      opts === null
        ? []
        : opts.fields.filter((f): f is string => typeof f === "string" && f.length > 0),
    picture: valueNamed(entity, "pic"),
    skills: countsIn(listNamed(entity, "temp")),
    carrying: countsIn(listNamed(entity, "pack")),
    gearTraits: bareStringsIn(listNamed(entity, "gear")),
    entity,
  };
}

/** Builds the content tables from the parsed JSON files. */
export function loadContent(files: {
  arms: { arms: (RawEntry & { attack: number; defend: number; skill: number })[] };
  monsters: { monsters: RawEntry[] };
  gear: { gear: GearDefinition[] };
}): Content {
  return {
    weapons: new Map(files.arms.arms.map((a) => [a.key, weaponFrom(a)])),
    monsters: new Map(files.monsters.monsters.map((m) => [m.key, monsterFrom(m)])),
    gear: new Map(files.gear.gear.map((g) => [g.key, g])),
  };
}
