package DCourt.Harness;

import DCourt.Items.List.itArms;
import DCourt.Items.List.itHero;
import DCourt.Items.List.itMonster;
import DCourt.Screens.Quest.arBattle;
import DCourt.Screens.Quest.arQuest;
import DCourt.Tools.Tools;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Records how the Java build actually behaves, so the TypeScript port can be checked against it
 * rather than against someone's reading of the source.
 *
 * <p>The whole thing rests on one property: {@code Tools.setSeed} makes the game deterministic.
 * Seed it, run a battle through the real {@code arQuest}/{@code arBattle} constructors, and the
 * same seed gives byte-identical output every time. So the baseline is a plain text file and parity
 * is a diff.
 *
 * <p>Nothing here touches game code. It drives the real classes headlessly -- no display is needed,
 * which is why this could be built without first untangling combat from the UI.
 *
 * <p>Run with {@code ./gradlew baseline}. Output goes to {@code baseline/baseline.txt}.
 */
public final class Baseline {

  /**
   * Bumped whenever the recording format changes, so a stale baseline cannot be diffed silently.
   */
  private static final String FORMAT = "1";

  private Baseline() {}

  public static void main(String[] args) throws Exception {
    Path out = Path.of(args.length > 0 ? args[0] : "baseline/baseline.txt");
    Files.createDirectories(out.getParent());

    Harness.boot();

    try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(out))) {
      w.println("# RustyDagger characterisation baseline, format " + FORMAT);
      w.println("# Generated by ./gradlew baseline -- do not hand-edit.");
      w.println("# Every line is an observed outcome of the Java build. The TypeScript port must");
      w.println(
          "# reproduce this file exactly. A diff here is a port defect, not a formatting nit.");
      w.println();

      rngPrimitives(w);
      levelling(w);
      combat(w);
      decay(w);
    }

    System.out.println("wrote " + out.toAbsolutePath() + " (" + Files.size(out) + " bytes)");
  }

  /**
   * The four random primitives every other rule is built on. If these diverge nothing downstream
   * can possibly match, so they are recorded first and are the first place to look at a parity
   * failure.
   */
  private static void rngPrimitives(PrintWriter w) {
    w.println("== RNG PRIMITIVES ==");
    for (int seed : new int[] {0, 1, 42, 12345, 999999}) {
      Tools.setSeed(seed);
      StringBuilder roll = new StringBuilder();
      for (int i = 0; i < 20; i++) {
        roll.append(Tools.roll(100)).append(',');
      }
      w.println("roll(100) seed=" + seed + " -> " + roll);

      Tools.setSeed(seed);
      StringBuilder twice = new StringBuilder();
      for (int i = 0; i < 20; i++) {
        twice.append(Tools.twice(3)).append(',');
      }
      w.println("twice(3)  seed=" + seed + " -> " + twice);

      Tools.setSeed(seed);
      StringBuilder contest = new StringBuilder();
      for (int i = 0; i < 20; i++) {
        contest.append(Tools.contest(30, 20) ? 'T' : 'F');
      }
      w.println("contest(30,20) seed=" + seed + " -> " + contest);

      Tools.setSeed(seed);
      StringBuilder next = new StringBuilder();
      for (int i = 0; i < 10; i++) {
        next.append(Tools.nextInt()).append(',');
      }
      w.println("nextInt() seed=" + seed + " -> " + next);
    }
    w.println();
  }

  /** The experience curve, which decides how the whole game paces. */
  private static void levelling(PrintWriter w) {
    w.println("== LEVELLING ==");
    itHero h = Harness.hero("Curve", 20, 20, 20, 10, 10, 10);
    for (int level = 1; level <= 30; level++) {
      Harness.setLevel(h, level);
      w.println("level=" + level + " raise=" + Harness.raise(h) + " baseQuests=" + h.getQuests());
    }
    w.println();
  }

  /**
   * Every monster in the game fought by four hero builds at five seeds. The full battle text is
   * recorded, not a summary: it encodes the swing count, who went first, every hit's power band and
   * every wound's severity, so a divergence anywhere in the round shows up here.
   */
  private static void combat(PrintWriter w) {
    w.println("== COMBAT ==");
    int[][] builds = {
      {10, 10, 10, 5, 5, 5}, // a fresh character
      {30, 20, 20, 20, 15, 25}, // mid-game
      {80, 40, 40, 60, 50, 70}, // well geared
      {200, 90, 90, 150, 120, 180}, // late game
    };
    List<String> monsters = Harness.monsterKeys();
    for (String key : monsters) {
      for (int b = 0; b < builds.length; b++) {
        int[] v = builds[b];
        for (int seed : new int[] {1, 7, 42, 1234, 98765}) {
          itHero h = Harness.hero("H" + b, v[0], v[1], v[2], v[3], v[4], v[5]);
          itMonster mob = Harness.monster(key);
          if (mob == null) {
            continue;
          }
          String prefix = "monster=" + key + " build=" + b + " seed=" + seed;
          Tools.setSeed(seed);
          try {
            arQuest q = new arQuest(null, 10, "baseline", mob);
            arBattle battle = new arBattle(q, "baseline");
            w.println(
                prefix
                    + " | text="
                    + Harness.oneLine(Harness.battleText(battle))
                    + " | hero="
                    + Harness.agentState(h)
                    + " | mob="
                    + Harness.agentState(mob));
          } catch (RuntimeException e) {
            // Recorded rather than swallowed: a monster that throws is a fact about the
            // game, and the port has to be told about it rather than quietly matching a
            // baseline that skipped it.
            w.println(prefix + " | THREW=" + e.getClass().getName() + ": " + e.getMessage());
          }
        }
      }
    }
    w.println();
  }

  /** Gear wears out as you use it; the rate and the amount both matter to how the economy feels. */
  private static void decay(PrintWriter w) {
    w.println("== DECAY ==");
    for (String key : Harness.armsKeys()) {
      for (int rate : new int[] {2, 5, 20}) {
        itArms a = Harness.arms(key);
        if (a == null) {
          continue;
        }
        Tools.setSeed(4242);
        StringBuilder hits = new StringBuilder();
        for (int i = 0; i < 40; i++) {
          hits.append(a.decay(rate) ? '1' : '0');
        }
        w.println(
            "item="
                + key
                + " rate="
                + rate
                + " decayed="
                + hits
                + " -> a="
                + a.getAttack()
                + " d="
                + a.getDefend()
                + " s="
                + a.getSkill());
      }
    }
    w.println();
  }
}
