package DCourt.Harness;

import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Records how the Java build behaves, so the TypeScript port can be checked against it rather than
 * against someone's reading of the source.
 *
 * <p>Parity is defined in two halves, deliberately, because one definition cannot do both jobs:
 *
 * <ul>
 *   <li>{@code baseline/rules.txt} — the arithmetic, characterised as functions with every input
 *       stated and every output a number. Checked <b>exactly</b>. A diff is a port defect.
 *   <li>{@code baseline/distributions.txt} — how the game actually plays over large samples.
 *       Checked by <b>shape</b>. A port is allowed to consume randomness in a different order; it
 *       is not allowed to play differently.
 * </ul>
 *
 * <p>The split exists because the obvious approach is wrong in two ways. Recording battle prose
 * would freeze the port's wording to the 1997 text, when the whole point of the rewrite is a freer
 * presentation. And demanding byte-identical replay would force the port to mirror the old code's
 * call order — {@code arBattle}'s constructor consumes randomness before the fight even starts — so
 * a correct rewrite would fail parity for reasons unrelated to the rules.
 *
 * <p>Nothing here changes game code. It drives the real classes headlessly. Run with {@code
 * ./gradlew baseline}.
 */
public final class Baseline {

  /**
   * Bumped whenever the recording format changes, so a stale baseline cannot be diffed silently.
   */
  private static final String FORMAT = "4";

  private Baseline() {}

  public static void main(String[] args) throws Exception {
    Path dir = Path.of(args.length > 0 ? args[0] : "baseline");
    Files.createDirectories(dir);

    Harness.boot();

    write(dir.resolve("rules.txt"), Rules::write);
    write(dir.resolve("distributions.txt"), Distributions::write);

    System.out.println("wrote " + dir.toAbsolutePath());
  }

  private static void write(Path out, java.util.function.Consumer<PrintWriter> body)
      throws Exception {
    try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(out))) {
      w.println("# RustyDagger parity baseline, format " + FORMAT);
      w.println("# Generated by ./gradlew baseline -- do not hand-edit.");
      body.accept(w);
    }
    System.out.println("  " + out.getFileName() + " (" + Files.size(out) + " bytes)");
  }
}
